apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: entities-api
data:
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  DB_SSLMODE: "disable"
  JWT_TTL: "24h"
  GIN_MODE: "release"
