apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: entities-api
type: Opaque
data:
  POSTGRES_USER: YWRtaW5fdXNlcg==
  POSTGRES_PASSWORD: U2VuaGExMjM=
  POSTGRES_DB: ZGJfbWVjYW5pY2FfeHB0bw==
  JWT_SECRET: Y2hhdmVfbXVpdG9fc2VndXJh
