apiVersion: v1
kind: Service
metadata:
  name: entities-api-service
  namespace: entities-api
spec:
  selector:
    app: entities-api
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
